import {
  auditEventSchema,
  nodeSummarySchema,
  sessionSchema,
  taskDetailSchema,
  type AuditEvent,
  type NodeSummary,
  type SessionInfo,
  type TaskDetail,
} from "@/shared/api/contracts"

const rawSession = {
  id: "user_wentx",
  name: "Wentx",
  role: "operator",
}

const rawNodes = [
  {
    id: "sg-prod-01",
    hostname: "sg-prod-01",
    region: "Singapore",
    os: "Ubuntu 22.04",
    version: "agent-0.2.1",
    tags: ["prod", "web"],
    status: "online",
    busy: true,
    lastSeen: "2026-03-19T14:22:00Z",
    metrics: { cpu: 68, memory: 59, disk: 72 },
  },
  {
    id: "us-east-02",
    hostname: "us-east-02",
    region: "Virginia",
    os: "Ubuntu 24.04",
    version: "agent-0.2.1",
    tags: ["prod", "api"],
    status: "online",
    busy: false,
    lastSeen: "2026-03-19T14:22:00Z",
    metrics: { cpu: 24, memory: 42, disk: 61 },
  },
  {
    id: "jp-tokyo-01",
    hostname: "jp-tokyo-01",
    region: "Tokyo",
    os: "Debian 12",
    version: "agent-0.2.0",
    tags: ["edge", "nginx"],
    status: "stale",
    busy: false,
    lastSeen: "2026-03-19T14:18:00Z",
    metrics: { cpu: 16, memory: 47, disk: 54 },
  },
  {
    id: "de-fra-03",
    hostname: "de-fra-03",
    region: "Frankfurt",
    os: "Ubuntu 22.04",
    version: "agent-0.2.1",
    tags: ["db", "prod"],
    status: "online",
    busy: false,
    lastSeen: "2026-03-19T14:22:00Z",
    metrics: { cpu: 31, memory: 64, disk: 48 },
  },
  {
    id: "hk-01",
    hostname: "hk-01",
    region: "Hong Kong",
    os: "Ubuntu 20.04",
    version: "agent-0.1.9",
    tags: ["legacy"],
    status: "offline",
    busy: false,
    lastSeen: "2026-03-19T13:42:00Z",
    metrics: { cpu: 0, memory: 0, disk: 0 },
  },
] as const

const rawTasks = [
  {
    id: "task_20260319_001",
    mode: "ai_agent",
    inputText: "检查所有在线节点的系统负载和磁盘占用",
    target: ["all"],
    createdAt: "2026-03-19T14:15:00Z",
    status: "running",
    approvalStatus: "not_required",
    plan: {
      targetNodes: ["sg-prod-01", "us-east-02", "jp-tokyo-01", "de-fra-03"],
      summary: "巡检在线节点的系统负载、磁盘使用率和 Docker 基础状态。",
      estimatedImpact: "只读诊断，不修改服务。",
      riskLevel: "low",
      requiresApproval: false,
      steps: [
        {
          id: "step_1",
          action: "system_status",
          args: { sample_window: "5m" },
          risk: "low",
        },
        {
          id: "step_2",
          action: "disk_usage",
          args: { mount: "/" },
          risk: "low",
        },
        {
          id: "step_3",
          action: "docker_ps",
          args: { format: "summary" },
          risk: "low",
        },
      ],
    },
    aggregate: {
      total: 5,
      success: 1,
      failed: 0,
      offlineSkipped: 1,
      running: 3,
    },
    summary:
      "广播巡检已开始。sg-prod-01 CPU 负载偏高，jp-tokyo-01 心跳偏旧，hk-01 已离线跳过。",
    executions: [
      {
        id: "exec_001_sg",
        taskId: "task_20260319_001",
        nodeId: "sg-prod-01",
        status: "running",
        startedAt: "2026-03-19T14:15:05Z",
        exitCode: null,
        stdoutTail: "load average: 2.24 2.08 1.94\nDisk /: 72%\nDocker: 14 containers",
        stderrTail: "",
        streamSummary: "stdout · load average + docker summary",
      },
      {
        id: "exec_001_us",
        taskId: "task_20260319_001",
        nodeId: "us-east-02",
        status: "success",
        startedAt: "2026-03-19T14:15:05Z",
        finishedAt: "2026-03-19T14:15:11Z",
        exitCode: 0,
        stdoutTail: "load average: 0.84 0.70 0.61\nDisk /: 61%\nDocker: 8 containers",
        stderrTail: "",
        streamSummary: "completed · healthy",
      },
      {
        id: "exec_001_jp",
        taskId: "task_20260319_001",
        nodeId: "jp-tokyo-01",
        status: "dispatched",
        startedAt: "2026-03-19T14:15:06Z",
        exitCode: null,
        stdoutTail: "",
        stderrTail: "",
        streamSummary: "awaiting fresh heartbeat",
      },
      {
        id: "exec_001_de",
        taskId: "task_20260319_001",
        nodeId: "de-fra-03",
        status: "queued",
        exitCode: null,
        stdoutTail: "",
        stderrTail: "",
        streamSummary: "queued on control plane",
      },
    ],
  },
  {
    id: "task_20260319_002",
    mode: "ai_agent",
    inputText: "重启东京节点的 nginx",
    target: ["jp-tokyo-01"],
    createdAt: "2026-03-19T14:08:00Z",
    status: "waiting_approval",
    approvalStatus: "pending",
    plan: {
      targetNodes: ["jp-tokyo-01"],
      summary: "重启 jp-tokyo-01 上的 nginx 服务。",
      estimatedImpact: "会短暂影响该节点入口流量。",
      riskLevel: "medium",
      requiresApproval: true,
      steps: [
        {
          id: "step_1",
          action: "service_status",
          args: { service: "nginx" },
          risk: "low",
        },
        {
          id: "step_2",
          action: "restart_service",
          args: { service: "nginx" },
          risk: "medium",
        },
      ],
    },
    aggregate: {
      total: 1,
      success: 0,
      failed: 0,
      offlineSkipped: 0,
      running: 0,
    },
    summary: "等待审批后才会下发到节点执行。",
    executions: [],
  },
  {
    id: "task_20260319_003",
    mode: "ai_agent",
    inputText: "看看 sg-prod-01 为什么 502",
    target: ["sg-prod-01"],
    createdAt: "2026-03-19T13:52:00Z",
    status: "success",
    approvalStatus: "not_required",
    plan: {
      targetNodes: ["sg-prod-01"],
      summary: "诊断 nginx、应用进程和最近错误日志。",
      estimatedImpact: "只读诊断，不修改服务。",
      riskLevel: "low",
      requiresApproval: false,
      steps: [
        {
          id: "step_1",
          action: "service_status",
          args: { service: "nginx" },
          risk: "low",
        },
        {
          id: "step_2",
          action: "tail_log",
          args: { file: "/var/log/nginx/error.log", lines: "100" },
          risk: "low",
        },
      ],
    },
    aggregate: {
      total: 1,
      success: 1,
      failed: 0,
      offlineSkipped: 0,
      running: 0,
    },
    summary: "应用 upstream 连接耗尽导致 502，建议优先检查 worker 数和连接池上限。",
    executions: [
      {
        id: "exec_003_sg",
        taskId: "task_20260319_003",
        nodeId: "sg-prod-01",
        status: "success",
        startedAt: "2026-03-19T13:52:10Z",
        finishedAt: "2026-03-19T13:52:19Z",
        exitCode: 0,
        stdoutTail: "nginx active\nupstream timed out (110: Connection timed out)",
        stderrTail: "",
        streamSummary: "completed · upstream timeout isolated",
      },
    ],
  },
] as const

const rawAudits = [
  {
    id: "audit_001",
    taskId: "task_20260319_001",
    actorId: "user_wentx",
    action: "task_planned",
    description: "低风险广播巡检已生成计划并自动进入执行。",
    createdAt: "2026-03-19T14:15:01Z",
  },
  {
    id: "audit_002",
    taskId: "task_20260319_001",
    actorId: "system",
    action: "task_execution_started",
    description: "已向 4 个在线节点分发执行。",
    createdAt: "2026-03-19T14:15:05Z",
  },
  {
    id: "audit_003",
    taskId: "task_20260319_002",
    actorId: "user_wentx",
    action: "task_approval_requested",
    description: "中风险计划等待人工审批。",
    createdAt: "2026-03-19T14:08:03Z",
  },
  {
    id: "audit_004",
    taskId: "task_20260319_003",
    actorId: "system",
    action: "task_summary_generated",
    description: "502 诊断已完成并生成 AI 摘要。",
    createdAt: "2026-03-19T13:52:21Z",
  },
] as const

export const mockSession: SessionInfo = sessionSchema.parse(rawSession)
export const mockNodes: NodeSummary[] = nodeSummarySchema.array().parse(rawNodes)
export const mockTasks: TaskDetail[] = taskDetailSchema.array().parse(rawTasks)
export const mockAudits: AuditEvent[] = auditEventSchema.array().parse(rawAudits)
